POST http://localhost:4002/login
Content-Type: application/json

{
    "user": "ion",
    "pass": "smecheru"
}

###

GET http://localhost:4001/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaW9uIiwiaWF0IjoxNjA2MTQwMTQ5fQ.ycigAX55iM92QHX04joiWnSIgKP8uXLYrJjoEuK9ZpE
